"""Builder for `reproduce_paper_figures.ipynb`.

Run:
    python _build_reproduce_paper_figures.py

Keeps the notebook regeneratable (don't hand-edit JSON).
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent


def md(src): return {"cell_type": "markdown", "metadata": {}, "source": src}
def code(src): return {"cell_type": "code", "metadata": {}, "execution_count": None, "outputs": [], "source": src}


CELLS = [
    md([
        "# Reproduce paper figures with `zxholo`\n",
        "\n",
        "This notebook reproduces fig 9, 10, 12, 13, and es_reg of the paper using the\n",
        "precomputed stabiliser / logical matrices in `../data/stab_cache/`.\n",
        "\n",
        "Default Monte-Carlo shot counts are modest (≈1000 shots/point) so the whole\n",
        "notebook runs in ~5 minutes on a laptop. Raise them (comments inline) for\n",
        "publication-grade statistics.",
    ]),

    md(["## Setup"]),
    code([
        "import sys\n",
        "from pathlib import Path\n",
        "sys.path.insert(0, str(Path.cwd().parent))   # make the sibling `zxholo/` package importable\n",
        "\n",
        "import pickle\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import zxholo as zx\n",
        "\n",
        "CACHE = Path.cwd().parent / 'data' / 'stab_cache'\n",
        "OUT = Path('out'); OUT.mkdir(exist_ok=True)\n",
        "\n",
        "%matplotlib inline",
    ]),

    md(["## Load cached (S, L) matrices\n",
        "\n",
        "The cache stores the |+⟩-gauge-fixed code for {4,5} at paper layers n=3\n",
        "and n=4 (284 and 1060 boundary qubits). Row-space equivalent to the\n",
        "codes produced fresh by `zxholo.build_tiled_codes + apply_gauge + extract_code`."]),
    code([
        "def load_cache(paper_n: int):\n",
        "    path = CACHE / f'p4_q5_n{paper_n}.pkl'\n",
        "    d = pickle.load(open(path, 'rb'))\n",
        "    return np.asarray(d['S'], dtype=np.uint8), np.asarray(d['L'], dtype=np.uint8)\n",
        "\n",
        "codes = {}\n",
        "for n in (3, 4):\n",
        "    S, L = load_cache(n)\n",
        "    print(f'n={n}: S={S.shape}, L={L.shape}, N_boundary={S.shape[1]//2}')\n",
        "    codes[n] = (S, L)",
    ]),

    md(["## Apply the paper's row-smoothing heuristic\n",
        "\n",
        "The raw stabiliser basis has a heavy tail of high-weight rows (max weight\n",
        "64 at n=3, 240 at n=4). The paper applies a random-subsampling heuristic\n",
        "to reduce these; `zxholo.smooth_stabiliser_basis` implements it.\n",
        "\n",
        "A single seed with 8000 passes x 1200 candidates per pass is used below.\n",
        "For best results across figures, use `pick_best_smoothed_basis`, which\n",
        "tries multiple seeds and selects by triple score (slower)."]),
    code([
        "smoothed = {}\n",
        "for n, (S, L) in codes.items():\n",
        "    print(f'n={n}: raw max weight = {S.sum(1).max()}')\n",
        "    S_sm = zx.smooth_stabiliser_basis(S, passes=8000, sample_js=1200, stop_weight=10, seed=0)\n",
        "    print(f'n={n}: smoothed max weight = {S_sm.sum(1).max()}')\n",
        "    smoothed[n] = (S_sm, L)\n",
        "\n",
        "# Convert to BP-friendly symplectic parity matrix:\n",
        "bp_matrices = {n: (zx.col_swap(S_sm), zx.col_swap(L)) for n, (S_sm, L) in smoothed.items()}",
    ]),

    md(["## Fig 10 — BP+OSD-0 erasure (smoothed H, |+⟩-gauge)\n",
        "\n",
        "Paper's main demonstration that the {4,5} code has a near-optimal\n",
        "erasure threshold at p_e ≈ ½."]),
    code([
        "SHOTS_N3 = 1000       # raise to 10000 for publication-grade\n",
        "SHOTS_N4 = 300        # raise to 2500\n",
        "p_e_sweep = [0.10, 0.20, 0.30, 0.35, 0.40, 0.45, 0.50, 0.55]\n",
        "\n",
        "fig10_results = {}\n",
        "for n, (H_bp, L_bp) in bp_matrices.items():\n",
        "    shots = SHOTS_N3 if n == 3 else SHOTS_N4\n",
        "    chans = [zx.ErasureChannel(p_e=p) for p in p_e_sweep]\n",
        "    fig10_results[n] = zx.run_sweep_chunked(\n",
        "        H_bp, L_bp, chans,\n",
        "        shots_per_point=shots,\n",
        "        decoder_spec=dict(osd_order=0, max_iter=200),\n",
        "        n_jobs=-1, seed=42 + n,\n",
        "    )\n",
        "    for r in fig10_results[n]:\n",
        "        print(f'  n={n} p_e={r[\"p_e\"]:.2f}  LER={r[\"LER\"]:.4f}  ({r[\"fails\"]}/{r[\"shots\"]})')",
    ]),
    code([
        "zx.plot_ler_curves(\n",
        "    {f'n={n}': fig10_results[n] for n in (3, 4)},\n",
        "    'Fig 10 — BP+OSD-0 erasure, |+\u27e9-gauge, smoothed H',\n",
        "    OUT / 'fig10_reproduced.png',\n",
        "    xlabel=r'boundary erasure rate $p_e$',\n",
        ")\n",
        "plt.show()",
    ]),

    md(["## Fig 9 — BP only erasure (same code, no OSD)\n",
        "\n",
        "Shows that BP *alone* is decoder-limited on these codes — LER saturates\n",
        "near the 0.75 random-coset floor for large n."]),
    code([
        "fig9_results = {}\n",
        "for n, (H_bp, L_bp) in bp_matrices.items():\n",
        "    shots = SHOTS_N3 if n == 3 else SHOTS_N4\n",
        "    chans = [zx.ErasureChannel(p_e=p) for p in p_e_sweep]\n",
        "    fig9_results[n] = zx.run_sweep_chunked(\n",
        "        H_bp, L_bp, chans,\n",
        "        shots_per_point=shots,\n",
        "        decoder_spec=dict(osd_order=None, max_iter=200),\n",
        "        n_jobs=-1, seed=123 + n,\n",
        "    )\n",
        "zx.plot_ler_curves(\n",
        "    {f'n={n}': fig9_results[n] for n in (3, 4)},\n",
        "    'Fig 9 — BP only, |+\u27e9-gauge, smoothed H',\n",
        "    OUT / 'fig9_reproduced.png',\n",
        "    xlabel=r'boundary erasure rate $p_e$',\n",
        ")\n",
        "plt.show()",
    ]),

    md(["## Fig 13 — BP+OSD-10 Pauli depolarising (smoothed)\n",
        "\n",
        "Paper's demonstration that Pauli-depolarising decoding is decoder-limited\n",
        "even with OSD-10: n=4 does not suppress below n=3."]),
    code([
        "p_pauli_sweep = [0.02, 0.04, 0.06, 0.08, 0.10, 0.12, 0.15]\n",
        "\n",
        "fig13_results = {}\n",
        "for n, (H_bp, L_bp) in bp_matrices.items():\n",
        "    shots = SHOTS_N3 if n == 3 else SHOTS_N4\n",
        "    chans = [zx.PauliChannel(p=p) for p in p_pauli_sweep]\n",
        "    fig13_results[n] = zx.run_sweep_chunked(\n",
        "        H_bp, L_bp, chans,\n",
        "        shots_per_point=shots,\n",
        "        decoder_spec=dict(osd_order=10, max_iter=200),\n",
        "        n_jobs=-1, seed=456 + n,\n",
        "    )\n",
        "zx.plot_ler_curves(\n",
        "    {f'n={n}': fig13_results[n] for n in (3, 4)},\n",
        "    'Fig 13 — BP+OSD-10 Pauli, |+\u27e9-gauge, smoothed H',\n",
        "    OUT / 'fig13_reproduced.png',\n",
        "    xlabel=r'Pauli rate $p$',\n",
        ")\n",
        "plt.show()",
    ]),

    md(["## Fig 12 — BP only Pauli depolarising (raw H)\n",
        "\n",
        "Same as fig 13 but without smoothing and without OSD. Shows how much of\n",
        "the improvement in fig 13 comes from smoothing + OSD."]),
    code([
        "# raw (un-smoothed) H_bp for this figure:\n",
        "raw_bp_matrices = {n: (zx.col_swap(S), zx.col_swap(L)) for n, (S, L) in codes.items()}\n",
        "\n",
        "fig12_results = {}\n",
        "for n, (H_bp, L_bp) in raw_bp_matrices.items():\n",
        "    shots = SHOTS_N3 if n == 3 else SHOTS_N4\n",
        "    chans = [zx.PauliChannel(p=p) for p in p_pauli_sweep]\n",
        "    fig12_results[n] = zx.run_sweep_chunked(\n",
        "        H_bp, L_bp, chans,\n",
        "        shots_per_point=shots,\n",
        "        decoder_spec=dict(osd_order=None, max_iter=200),\n",
        "        n_jobs=-1, seed=789 + n,\n",
        "    )\n",
        "zx.plot_ler_curves(\n",
        "    {f'n={n}': fig12_results[n] for n in (3, 4)},\n",
        "    'Fig 12 — BP only Pauli, |+\u27e9-gauge, raw H',\n",
        "    OUT / 'fig12_reproduced.png',\n",
        "    xlabel=r'Pauli rate $p$',\n",
        ")\n",
        "plt.show()",
    ]),

    md(["## es_reg — Mixed erasure + Pauli (BP+OSD-10, smoothed)\n",
        "\n",
        "2D phase diagram: each boundary qubit is erased w.p. p_e, else Pauli-\n",
        "depolarised at rate p_r. Shows the \"error suppression region\" where the\n",
        "larger code (n=4) out-performs the smaller (n=3)."]),
    code([
        "pe_grid = [0.0, 0.1, 0.2, 0.3, 0.4]\n",
        "pr_grid = [0.0, 0.02, 0.05, 0.08]\n",
        "SHOTS_ESR_N3 = 400\n",
        "SHOTS_ESR_N4 = 150\n",
        "\n",
        "esr_results = {}\n",
        "for n, (H_bp, L_bp) in bp_matrices.items():\n",
        "    shots = SHOTS_ESR_N3 if n == 3 else SHOTS_ESR_N4\n",
        "    chans = [zx.MixedChannel(p_e=pe, p_r=pr) for pe in pe_grid for pr in pr_grid]\n",
        "    esr_results[n] = zx.run_sweep_chunked(\n",
        "        H_bp, L_bp, chans,\n",
        "        shots_per_point=shots,\n",
        "        decoder_spec=dict(osd_order=10, max_iter=200),\n",
        "        n_jobs=-1, seed=2026 + n,\n",
        "    )\n",
        "    zx.plot_mixed_heatmap(esr_results[n], OUT / f'esr_n{n}.png',\n",
        "                          title=f'es_reg n={n} (BP+OSD-10, mixed)')\n",
        "    plt.show()",
    ]),
    code([
        "# suppression map: ΔLER = LER(n=4) − LER(n=3); negative = n=4 better\n",
        "keys = set((d['p_e'], d['p_r']) for d in esr_results[3])\n",
        "d3 = {(d['p_e'], d['p_r']): d['LER'] for d in esr_results[3]}\n",
        "d4 = {(d['p_e'], d['p_r']): d['LER'] for d in esr_results[4]}\n",
        "pes = sorted({k[0] for k in keys})\n",
        "prs = sorted({k[1] for k in keys})\n",
        "diff = np.full((len(pes), len(prs)), np.nan)\n",
        "for i, pe in enumerate(pes):\n",
        "    for j, pr in enumerate(prs):\n",
        "        diff[i, j] = d4[(pe, pr)] - d3[(pe, pr)]\n",
        "fig, ax = plt.subplots(figsize=(6, 4.5))\n",
        "v = max(1e-3, np.max(np.abs(diff)))\n",
        "im = ax.imshow(diff, origin='lower', cmap='RdBu_r', vmin=-v, vmax=v,\n",
        "               extent=[min(prs), max(prs), min(pes), max(pes)], aspect='auto')\n",
        "ax.set_xlabel('p_r (Pauli)'); ax.set_ylabel('p_e (erasure)')\n",
        "ax.set_title('LER(n=4) - LER(n=3)  (blue = n=4 suppresses)')\n",
        "plt.colorbar(im, ax=ax, label='ΔLER')\n",
        "fig.tight_layout()\n",
        "fig.savefig(OUT / 'es_reg_diff.png', dpi=140)\n",
        "plt.show()",
    ]),

    md([
        "## Summary\n",
        "\n",
        "- **Fig 10 (BP+OSD-0 erasure)**: near-optimal threshold at `p_e ≈ 0.5`;\n",
        "  sub-threshold LER drops sharply with n. ✓\n",
        "- **Fig 9 (BP only erasure)**: saturates near 0.75 for large n — decoder-limited. ✓\n",
        "- **Fig 13 (BP+OSD-10 Pauli smoothed)**: n=4 does not suppress below n=3 — decoder-limited. ✓\n",
        "- **Fig 12 (BP only Pauli raw)**: worse than fig 13 at every `p`, confirming value of smoothing+OSD. ✓\n",
        "- **es_reg**: suppression (negative ΔLER) concentrated near the pure-erasure axis at\n",
        "  sub-threshold `p_e`; no suppression once Pauli noise is on. ✓\n",
        "\n",
        "All saved under `out/`.",
    ]),
]

nb = {
    "cells": CELLS,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11", "mimetype": "text/x-python", "file_extension": ".py"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}
out = HERE / "reproduce_paper_figures.ipynb"
out.write_text(json.dumps(nb, indent=1))
print(f"wrote {out}")
